# Generated by Django 3.1.7 on 2021-03-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='bookjournalbase_ptr',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookJournalBase',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
