JOURNAL_TYPE_BULLET = 1
JOURNAL_TYPE_FOOD = 2
JOURNAL_TYPE_TRAVEL = 3
JOURNAL_TYPE_SPORT = 4
JOURNAL_TYPES = (
    (JOURNAL_TYPE_BULLET, 'Bullet'),
    (JOURNAL_TYPE_FOOD, 'Food'),
    (JOURNAL_TYPE_TRAVEL, 'Travel'),
    (JOURNAL_TYPE_SPORT, 'Sport'),
)

USER_ROLE_SUPER_USER = 1
USER_ROLE_COMPANY_DIRECTOR = 2
USER_ROLE_HR_MANAGER = 3
USER_ROLE_EMPLOYEE = 4
USER_ROLE_DEPARTMENT_DIRECTOR = 5
USER_ROLES = (
    (USER_ROLE_SUPER_USER, 'super admin'),
    (USER_ROLE_COMPANY_DIRECTOR, 'company director'),
    (USER_ROLE_HR_MANAGER, 'hr manager'),
    (USER_ROLE_EMPLOYEE, 'employee'),
    (USER_ROLE_DEPARTMENT_DIRECTOR, 'department director'),
)
